// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat-services.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterUsernameRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUsernameRequest) Reset()         { *m = RegisterUsernameRequest{} }
func (m *RegisterUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUsernameRequest) ProtoMessage()    {}
func (*RegisterUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958e405a97572da2, []int{0}
}

func (m *RegisterUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUsernameRequest.Unmarshal(m, b)
}
func (m *RegisterUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUsernameRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUsernameRequest.Merge(m, src)
}
func (m *RegisterUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUsernameRequest.Size(m)
}
func (m *RegisterUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUsernameRequest proto.InternalMessageInfo

func (m *RegisterUsernameRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RegisterUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RegisterUsernameResponse struct {
	Code                 string                    `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string                    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponseRegistration `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RegisterUsernameResponse) Reset()         { *m = RegisterUsernameResponse{} }
func (m *RegisterUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUsernameResponse) ProtoMessage()    {}
func (*RegisterUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958e405a97572da2, []int{1}
}

func (m *RegisterUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUsernameResponse.Unmarshal(m, b)
}
func (m *RegisterUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUsernameResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUsernameResponse.Merge(m, src)
}
func (m *RegisterUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUsernameResponse.Size(m)
}
func (m *RegisterUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUsernameResponse proto.InternalMessageInfo

func (m *RegisterUsernameResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RegisterUsernameResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RegisterUsernameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterUsernameResponse) GetData() *DataResponseRegistration {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponseRegistration struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	LoggedTime           string   `protobuf:"bytes,2,opt,name=loggedTime,proto3" json:"loggedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponseRegistration) Reset()         { *m = DataResponseRegistration{} }
func (m *DataResponseRegistration) String() string { return proto.CompactTextString(m) }
func (*DataResponseRegistration) ProtoMessage()    {}
func (*DataResponseRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_958e405a97572da2, []int{2}
}

func (m *DataResponseRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponseRegistration.Unmarshal(m, b)
}
func (m *DataResponseRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponseRegistration.Marshal(b, m, deterministic)
}
func (m *DataResponseRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponseRegistration.Merge(m, src)
}
func (m *DataResponseRegistration) XXX_Size() int {
	return xxx_messageInfo_DataResponseRegistration.Size(m)
}
func (m *DataResponseRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponseRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponseRegistration proto.InternalMessageInfo

func (m *DataResponseRegistration) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DataResponseRegistration) GetLoggedTime() string {
	if m != nil {
		return m.LoggedTime
	}
	return ""
}

type RequestChat struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Who                  string   `protobuf:"bytes,2,opt,name=who,proto3" json:"who,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChat) Reset()         { *m = RequestChat{} }
func (m *RequestChat) String() string { return proto.CompactTextString(m) }
func (*RequestChat) ProtoMessage()    {}
func (*RequestChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_958e405a97572da2, []int{3}
}

func (m *RequestChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChat.Unmarshal(m, b)
}
func (m *RequestChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChat.Marshal(b, m, deterministic)
}
func (m *RequestChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChat.Merge(m, src)
}
func (m *RequestChat) XXX_Size() int {
	return xxx_messageInfo_RequestChat.Size(m)
}
func (m *RequestChat) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChat.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChat proto.InternalMessageInfo

func (m *RequestChat) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *RequestChat) GetWho() string {
	if m != nil {
		return m.Who
	}
	return ""
}

func (m *RequestChat) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResponseChat struct {
	Code                 string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponseChat `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResponseChat) Reset()         { *m = ResponseChat{} }
func (m *ResponseChat) String() string { return proto.CompactTextString(m) }
func (*ResponseChat) ProtoMessage()    {}
func (*ResponseChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_958e405a97572da2, []int{4}
}

func (m *ResponseChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseChat.Unmarshal(m, b)
}
func (m *ResponseChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseChat.Marshal(b, m, deterministic)
}
func (m *ResponseChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseChat.Merge(m, src)
}
func (m *ResponseChat) XXX_Size() int {
	return xxx_messageInfo_ResponseChat.Size(m)
}
func (m *ResponseChat) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseChat.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseChat proto.InternalMessageInfo

func (m *ResponseChat) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResponseChat) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ResponseChat) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseChat) GetData() *DataResponseChat {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponseChat struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	MessageStatus        string   `protobuf:"bytes,2,opt,name=messageStatus,proto3" json:"messageStatus,omitempty"`
	MessageTime          string   `protobuf:"bytes,3,opt,name=messageTime,proto3" json:"messageTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponseChat) Reset()         { *m = DataResponseChat{} }
func (m *DataResponseChat) String() string { return proto.CompactTextString(m) }
func (*DataResponseChat) ProtoMessage()    {}
func (*DataResponseChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_958e405a97572da2, []int{5}
}

func (m *DataResponseChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponseChat.Unmarshal(m, b)
}
func (m *DataResponseChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponseChat.Marshal(b, m, deterministic)
}
func (m *DataResponseChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponseChat.Merge(m, src)
}
func (m *DataResponseChat) XXX_Size() int {
	return xxx_messageInfo_DataResponseChat.Size(m)
}
func (m *DataResponseChat) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponseChat.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponseChat proto.InternalMessageInfo

func (m *DataResponseChat) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DataResponseChat) GetMessageStatus() string {
	if m != nil {
		return m.MessageStatus
	}
	return ""
}

func (m *DataResponseChat) GetMessageTime() string {
	if m != nil {
		return m.MessageTime
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterUsernameRequest)(nil), "v1.RegisterUsernameRequest")
	proto.RegisterType((*RegisterUsernameResponse)(nil), "v1.RegisterUsernameResponse")
	proto.RegisterType((*DataResponseRegistration)(nil), "v1.DataResponseRegistration")
	proto.RegisterType((*RequestChat)(nil), "v1.RequestChat")
	proto.RegisterType((*ResponseChat)(nil), "v1.ResponseChat")
	proto.RegisterType((*DataResponseChat)(nil), "v1.DataResponseChat")
}

func init() { proto.RegisterFile("chat-services.proto", fileDescriptor_958e405a97572da2) }

var fileDescriptor_958e405a97572da2 = []byte{
	// 588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0x13, 0x3b,
	0x14, 0x95, 0x93, 0xbc, 0xf6, 0xbd, 0xdb, 0xf6, 0x11, 0x99, 0xaa, 0x8c, 0x42, 0x85, 0x86, 0x11,
	0x82, 0x2a, 0xea, 0x64, 0x9a, 0xb4, 0xab, 0xb0, 0xe1, 0x4b, 0x62, 0x85, 0x04, 0x29, 0xec, 0xd8,
	0xb8, 0x33, 0x57, 0x1e, 0xd3, 0xc4, 0x1e, 0x6c, 0x4f, 0x0a, 0x12, 0x62, 0xc1, 0x4f, 0x28, 0x3b,
	0xfe, 0x16, 0x1b, 0x16, 0x2c, 0xd9, 0xf3, 0x17, 0xd0, 0x78, 0xdc, 0x90, 0x69, 0xe8, 0x8e, 0xd5,
	0xf8, 0x1e, 0x1f, 0x9f, 0x73, 0xef, 0xb1, 0x07, 0xae, 0xa7, 0x39, 0xb3, 0xb1, 0x41, 0x3d, 0x17,
	0x29, 0x9a, 0x41, 0xa1, 0x95, 0x55, 0xb4, 0x35, 0x1f, 0xf6, 0x76, 0xb9, 0x52, 0x7c, 0x8a, 0x09,
	0x2b, 0x44, 0xc2, 0xa4, 0x54, 0x96, 0x59, 0xa1, 0xa4, 0x67, 0xf4, 0xf6, 0xdd, 0x27, 0x8d, 0x39,
	0xca, 0xd8, 0x9c, 0x31, 0xce, 0x51, 0x27, 0xaa, 0x70, 0x8c, 0x55, 0x76, 0xf4, 0x14, 0x6e, 0x4c,
	0x90, 0x0b, 0x63, 0x51, 0xbf, 0x32, 0xa8, 0x25, 0x9b, 0xe1, 0x04, 0xdf, 0x96, 0x68, 0x2c, 0xed,
	0x42, 0x9b, 0x15, 0x22, 0x20, 0x21, 0xd9, 0xfb, 0x6f, 0x52, 0x2d, 0x69, 0x0f, 0xfe, 0x2d, 0x3d,
	0x29, 0x68, 0x39, 0x78, 0x51, 0x47, 0xe7, 0x04, 0x82, 0x55, 0x25, 0x53, 0x28, 0x69, 0x90, 0x52,
	0xe8, 0xa4, 0x2a, 0x43, 0xaf, 0xe5, 0xd6, 0x74, 0x07, 0xd6, 0x8c, 0x65, 0xb6, 0x34, 0x5e, 0xca,
	0x57, 0x34, 0x80, 0xf5, 0x19, 0x1a, 0xc3, 0x38, 0x06, 0x6d, 0xb7, 0x71, 0x51, 0xd2, 0x03, 0xe8,
	0x64, 0xcc, 0xb2, 0xa0, 0x13, 0x92, 0xbd, 0x8d, 0xd1, 0xee, 0x60, 0x3e, 0x1c, 0x3c, 0x61, 0x96,
	0x5d, 0xb8, 0xd4, 0xee, 0xda, 0x8d, 0x37, 0x71, 0xcc, 0xe8, 0x39, 0x04, 0x57, 0x31, 0xe8, 0x36,
	0xfc, 0x63, 0xd5, 0x29, 0x4a, 0xdf, 0x54, 0x5d, 0xd0, 0x5b, 0x00, 0x53, 0xc5, 0x39, 0x66, 0x2f,
	0xc5, 0x62, 0xc8, 0x25, 0x24, 0x7a, 0x01, 0x1b, 0x3e, 0x9f, 0xc7, 0x39, 0xb3, 0x6e, 0x08, 0x94,
	0x19, 0x6a, 0xaf, 0xe2, 0xab, 0x2a, 0xbb, 0xb3, 0x5c, 0xf9, 0xf3, 0xd5, 0xf2, 0xea, 0xb1, 0xa2,
	0x8f, 0xb0, 0x79, 0xd1, 0xa0, 0xd3, 0xfc, 0x3b, 0x61, 0xed, 0x35, 0xc2, 0xda, 0xbe, 0x1c, 0x56,
	0xe5, 0xe4, 0x43, 0x9a, 0x43, 0xf7, 0xf2, 0x4e, 0xe3, 0xa6, 0x49, 0xf3, 0xa6, 0xe9, 0x1d, 0xd8,
	0xf2, 0x26, 0xc7, 0xcb, 0x2d, 0x35, 0x41, 0x1a, 0xc2, 0x86, 0x07, 0x5c, 0x92, 0x75, 0x77, 0xcb,
	0xd0, 0xe8, 0x27, 0x81, 0xcd, 0xca, 0xec, 0xd8, 0xbf, 0x70, 0xfa, 0x01, 0xba, 0x97, 0x5f, 0x10,
	0xbd, 0x59, 0x35, 0x7e, 0xc5, 0x0b, 0xed, 0xed, 0xfe, 0x79, 0xb3, 0x9e, 0x23, 0x8a, 0x3f, 0x7d,
	0xfd, 0xf1, 0xb9, 0x75, 0x2f, 0x8a, 0x92, 0xf9, 0x30, 0x69, 0xfc, 0x4b, 0x89, 0xf6, 0x67, 0x62,
	0x96, 0xa6, 0xaa, 0x94, 0x76, 0x4c, 0xfa, 0x94, 0xc1, 0xff, 0xc7, 0x28, 0x33, 0x21, 0xf9, 0x33,
	0x1f, 0xe1, 0xb5, 0x5a, 0x7e, 0x71, 0xdb, 0xbd, 0x6e, 0x0d, 0xfc, 0xce, 0x29, 0xda, 0x77, 0x1e,
	0x77, 0xa3, 0xdb, 0xab, 0x1e, 0xa6, 0x16, 0x8b, 0xfd, 0xc8, 0x63, 0xd2, 0x7f, 0xf4, 0x9d, 0x9c,
	0x3f, 0xfc, 0x46, 0xa8, 0x86, 0xad, 0x06, 0x35, 0x7a, 0x0d, 0x5b, 0x55, 0xba, 0x0b, 0x80, 0x1e,
	0xe6, 0xd6, 0x16, 0x66, 0x9c, 0x24, 0x5c, 0xd8, 0xbc, 0x3c, 0x19, 0xa4, 0x6a, 0x96, 0x64, 0x22,
	0x3d, 0x7d, 0xcf, 0x51, 0xb3, 0x69, 0x26, 0x12, 0xf7, 0xf3, 0xc6, 0x0d, 0x95, 0xde, 0xce, 0x32,
	0xe3, 0x01, 0x9f, 0x31, 0x31, 0xad, 0x0e, 0x8e, 0xda, 0xc3, 0xc1, 0x41, 0x9f, 0x90, 0x51, 0x97,
	0x15, 0xc5, 0x54, 0xa4, 0xee, 0xf5, 0x27, 0x6f, 0x8c, 0x92, 0xe3, 0x15, 0x64, 0x72, 0x1f, 0xda,
	0x47, 0x07, 0x47, 0xf4, 0x08, 0xfa, 0x13, 0xb4, 0xa5, 0x96, 0x98, 0x85, 0x67, 0x39, 0xca, 0xd0,
	0xe6, 0x18, 0x6a, 0x34, 0xaa, 0xd4, 0x29, 0x86, 0x99, 0x42, 0x13, 0x4a, 0x65, 0x43, 0x7c, 0x27,
	0x8c, 0x1d, 0xd0, 0x35, 0xe8, 0x7c, 0x69, 0x91, 0xf5, 0x93, 0x35, 0xd7, 0xd5, 0xe1, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xdf, 0xf9, 0x1c, 0x02, 0xb9, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatServicesClient is the client API for ChatServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServicesClient interface {
	RegisterUsername(ctx context.Context, in *RegisterUsernameRequest, opts ...grpc.CallOption) (*RegisterUsernameResponse, error)
	SendingMessage(ctx context.Context, in *RequestChat, opts ...grpc.CallOption) (*ResponseChat, error)
}

type chatServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServicesClient(cc grpc.ClientConnInterface) ChatServicesClient {
	return &chatServicesClient{cc}
}

func (c *chatServicesClient) RegisterUsername(ctx context.Context, in *RegisterUsernameRequest, opts ...grpc.CallOption) (*RegisterUsernameResponse, error) {
	out := new(RegisterUsernameResponse)
	err := c.cc.Invoke(ctx, "/v1.ChatServices/RegisterUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServicesClient) SendingMessage(ctx context.Context, in *RequestChat, opts ...grpc.CallOption) (*ResponseChat, error) {
	out := new(ResponseChat)
	err := c.cc.Invoke(ctx, "/v1.ChatServices/SendingMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServicesServer is the server API for ChatServices service.
type ChatServicesServer interface {
	RegisterUsername(context.Context, *RegisterUsernameRequest) (*RegisterUsernameResponse, error)
	SendingMessage(context.Context, *RequestChat) (*ResponseChat, error)
}

// UnimplementedChatServicesServer can be embedded to have forward compatible implementations.
type UnimplementedChatServicesServer struct {
}

func (*UnimplementedChatServicesServer) RegisterUsername(ctx context.Context, req *RegisterUsernameRequest) (*RegisterUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUsername not implemented")
}
func (*UnimplementedChatServicesServer) SendingMessage(ctx context.Context, req *RequestChat) (*ResponseChat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendingMessage not implemented")
}

func RegisterChatServicesServer(s *grpc.Server, srv ChatServicesServer) {
	s.RegisterService(&_ChatServices_serviceDesc, srv)
}

func _ChatServices_RegisterUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServicesServer).RegisterUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChatServices/RegisterUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServicesServer).RegisterUsername(ctx, req.(*RegisterUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatServices_SendingMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestChat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServicesServer).SendingMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChatServices/SendingMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServicesServer).SendingMessage(ctx, req.(*RequestChat))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ChatServices",
	HandlerType: (*ChatServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUsername",
			Handler:    _ChatServices_RegisterUsername_Handler,
		},
		{
			MethodName: "SendingMessage",
			Handler:    _ChatServices_SendingMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat-services.proto",
}
